---
development:
  dialect: postgres
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/buffalo_bench_test?sslmode=disable"}}
  pool: {{envOr "DATABASE_POOL_SIZE" "5" }}
  password: {{envOr "DATABASE_PASSWORD" "mysecretpw" }}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/buffalo_bench_test?sslmode=disable"}}
  password: {{envOr "DATABASE_PASSWORD" "NONE" }}

production:
  url: {{envOr "DATABASE_URL" "NA"}}
  pool: {{envOr "DATABASE_POOL_SIZE" "200" }}
  password: {{envOr "DATABASE_PASSWORD" "NONE" }}
